name: OUH
version: '1.0-SNAPSHOT'
main: de.ben.oUH.OUH
api-version: '1.21'
commands:
  spawn:
    description: Teleportiert dich zum Spawn, wenn du 5 Sekunden stillstehst
    usage: /spawn
  help:
    description: Gibt dir nen Buch
    usage: /help
  pvp:
    description: Du kannst ken Pvp mehr
    usage: /pvp
  admin:
    description: Du kannst ken Pvp mehr
    usage: /pvp
  status:
    description: Setzt oder entfernt deinen Status im Tab
    usage: /status [name]
