name: OUH
version: '1.0-SNAPSHOT'
main: de.ben.oUH.OUH
api-version: '1.21'

softdepend:
  - PlaceholderAPI

commands:
  spawn:
    description: Teleportiert dich zum Spawn, wenn du 5 Sekunden stillstehst
    usage: /spawn
  help:
    description: Gibt dir ein Buch
    usage: /help
  pvp:
    description: PvP aktivieren/deaktivieren
    usage: /pvp
  admin:
    description: Admin-Menü öffnen
    usage: /admin
  status:
    description: Setzt oder entfernt deinen Status im Tab
    usage: /status [name]
